#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Admin_App_Coins.Resource", IsApplication=true)]

namespace Admin_App_Coins
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ButtonBorder = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int emblem = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int flag = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ImageBorderCoins = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ImageBorderCoinsRed = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ImageBorderCoinsYellow = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int LayoutCountCoins = 2130837510;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070016
			public const int ButtonCount = 2131165206;
			
			// aapt resource value: 0x7f070010
			public const int ButtonCountCategory = 2131165200;
			
			// aapt resource value: 0x7f07000b
			public const int CancelAddPeriod = 2131165195;
			
			// aapt resource value: 0x7f07001a
			public const int CheckBoxPeriod = 2131165210;
			
			// aapt resource value: 0x7f070005
			public const int ImageAddPeriodEmblem = 2131165189;
			
			// aapt resource value: 0x7f070004
			public const int ImageAddPeriodFlag = 2131165188;
			
			// aapt resource value: 0x7f07000e
			public const int ImageCategory = 2131165198;
			
			// aapt resource value: 0x7f070012
			public const int ImageCoins = 2131165202;
			
			// aapt resource value: 0x7f070022
			public const int ImageCountry = 2131165218;
			
			// aapt resource value: 0x7f070019
			public const int ImageEmblem = 2131165209;
			
			// aapt resource value: 0x7f070018
			public const int ImageFlag = 2131165208;
			
			// aapt resource value: 0x7f07001e
			public const int ImageRuler = 2131165214;
			
			// aapt resource value: 0x7f070002
			public const int Layout_add_period_item = 2131165186;
			
			// aapt resource value: 0x7f07000d
			public const int Layout_category_item = 2131165197;
			
			// aapt resource value: 0x7f070021
			public const int Layout_country_item = 2131165217;
			
			// aapt resource value: 0x7f070000
			public const int Layout_newperiod = 2131165184;
			
			// aapt resource value: 0x7f070017
			public const int Layout_period_item = 2131165207;
			
			// aapt resource value: 0x7f07001d
			public const int Layout_ruler_item = 2131165213;
			
			// aapt resource value: 0x7f070007
			public const int Name_Period = 2131165191;
			
			// aapt resource value: 0x7f070009
			public const int Period = 2131165193;
			
			// aapt resource value: 0x7f07000a
			public const int SaveAddPeriod = 2131165194;
			
			// aapt resource value: 0x7f070001
			public const int ScrollView_Period = 2131165185;
			
			// aapt resource value: 0x7f070023
			public const int Text_Country = 2131165219;
			
			// aapt resource value: 0x7f070015
			public const int Text_Name = 2131165205;
			
			// aapt resource value: 0x7f07000f
			public const int Text_Name_Category = 2131165199;
			
			// aapt resource value: 0x7f07001b
			public const int Text_Name_Period = 2131165211;
			
			// aapt resource value: 0x7f07001f
			public const int Text_Name_Ruler = 2131165215;
			
			// aapt resource value: 0x7f07001c
			public const int Text_Period_Year = 2131165212;
			
			// aapt resource value: 0x7f070013
			public const int Text_Price = 2131165203;
			
			// aapt resource value: 0x7f070020
			public const int Text_Ruler_Year = 2131165216;
			
			// aapt resource value: 0x7f070014
			public const int Text_Year = 2131165204;
			
			// aapt resource value: 0x7f070003
			public const int _Icon_Flag_Period = 2131165187;
			
			// aapt resource value: 0x7f070006
			public const int _Name_Period = 2131165190;
			
			// aapt resource value: 0x7f070008
			public const int _Period = 2131165192;
			
			// aapt resource value: 0x7f070028
			public const int _listView = 2131165224;
			
			// aapt resource value: 0x7f07000c
			public const int gridView1 = 2131165196;
			
			// aapt resource value: 0x7f07002a
			public const int gridView2 = 2131165226;
			
			// aapt resource value: 0x7f070025
			public const int listView = 2131165221;
			
			// aapt resource value: 0x7f070027
			public const int main_content = 2131165223;
			
			// aapt resource value: 0x7f07002c
			public const int menu_add = 2131165228;
			
			// aapt resource value: 0x7f07002d
			public const int menu_delete = 2131165229;
			
			// aapt resource value: 0x7f07002b
			public const int menu_edit = 2131165227;
			
			// aapt resource value: 0x7f070026
			public const int relativeLayout = 2131165222;
			
			// aapt resource value: 0x7f070011
			public const int relativeLayout1 = 2131165201;
			
			// aapt resource value: 0x7f070024
			public const int relativeLayoutcoins = 2131165220;
			
			// aapt resource value: 0x7f07002e
			public const int switch_edit = 2131165230;
			
			// aapt resource value: 0x7f070029
			public const int toolbar_edit_toolbar = 2131165225;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int AddPeriod = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int CategoryPages = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int ItemCategoryPages = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int ItemListCoins = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int ItemPeriodPages = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int ItemRulerPages = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int MainPage = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int PageCoins = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int PeriodPage = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int RulerPages = 2130968585;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f060000
			public const int edit_toolbar = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int menu_toolbar = 2131099649;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int ic_action_content = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ic_action_content_delete = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int ic_action_content_save = 2130903042;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050000
			public const int app_name = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
